Repository kubewarden/policy-sdk-rust, pull requests merged in 2024-02, with the labels that each got.

#129 feat: image manifest capability
  Cargo.toml
  src/host_capabilities/oci.rs
Labels: kind/feature

#132 fix: CertificateVerificationRequest{}.not_after as None if empty
  Cargo.toml
  src/host_capabilities/mod.rs
Labels: kind/bug

#135 fix!: renames OCI capability functions.
  src/host_capabilities/oci.rs
Labels: kind/breaking-change, kind/bug
