Repository kubewarden/policy-sdk-rust, pull requests merged in 2025-07, with the labels that each got.

#179 fix(kubernetes/can-i): follow other capabilities function signatures.
  src/host_capabilities/kubernetes.rs
Labels: kind/bug

#180 Revert "fix(deps): update rust crate schemars to v1"
  Cargo.toml
Labels: area/dependencies, kind/bug

#181 chore: bump version to v0.14.0.
  Cargo.toml
Labels: kind/chore

#184 chore(kubernetes/can-i): updates function documentation.
  src/host_capabilities/kubernetes.rs
Labels: kind/chore

#185 chore(Cargo.toml): bump v0.14.1 version.
  Cargo.toml
Labels: kind/chore

#187 fix(kubernetes/can-i): remove k8s object from can-i capability
  src/host_capabilities/kubernetes.rs
Labels: kind/bug

#188 chore: v0.14.2 version bump.
  Cargo.toml
Labels: kind/chore
